name: build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: '3.7'
          architecture: 'x64'
      
      - name: Setup PlatformIO
        run: |
          pip install -U https://github.com/platformio/platformio-core/archive/develop.zip
          platformio update

      - name: clone Marlin firmware
        uses: actions/checkout@v2
        with:
          repository: MarlinFirmware/Marlin

      - name: clone Marlin configurations
        uses: actions/checkout@v2
        with:
          repository: MarlinFirmware/Configurations
          path: Configurations

      - name: Copy Ender 3 V2 config files
        run: |
          cp 'Configurations/config/examples/Creality/Ender-3 V2/{Configuration.h,Configuration_adv.h,_Bootscreen.h,_Statusscreen.h}' Marlin/

      - name: Build Marlin
        run: |
          platformio run -t STM32F103RET6_creality

      - name: Archive firmware image
        uses: actions/upload-artifact@v2
        with:
          name: firmware.bin
          path: .pio/build/STM32F103RET6_creality/firmware-*.bin
  
