name: build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      RELEASE: 2.0.8.2

    steps:
      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: '3.7'
          architecture: 'x64'

      - name: Setup PlatformIO
        run: |
          pip install -U https://github.com/platformio/platformio-core/archive/develop.zip
          platformio update

      - name: Prepare repo
        uses: actions/checkout@v2

      - name: Clone Marlin firmware
        uses: actions/checkout@v2
        with:
          repository: MarlinFirmware/Marlin
          ref: ${{ env.RELEASE }}
          path: Marlin

      - name: Clone Marlin configurations
        uses: actions/checkout@v2
        with:
          repository: MarlinFirmware/Configurations
          ref: ${{ env.RELEASE }}
          path: Configurations

      - name: Copy Ender 3 V2 config files
        run: |
          cp Configuration.h Marlin/Marlin/
          cp Configuration_adv.h Marlin/Marlin/
          cp 'Configurations/config/examples/Creality/Ender-3 V2/_Bootscreen.h' Marlin/Marlin/
          cp 'Configurations/config/examples/Creality/Ender-3 V2/_Statusscreen.h' Marlin/Marlin/

      - name: Apply source patch
        run: patch -p1 < Marlin.patch

      - name: Build Marlin
        run: cd Marlin && platformio run -e STM32F103RET6_creality

      - name: Copy release files
        run: |
          mkdir -p release
          cp -r 'Configurations/config/examples/Creality/Ender-3 V2/DWIN_SET' release/
          cp Marlin/.pio/build/STM32F103RET6_creality/firmware-*.bin release/

      - name: Archive firmware
        uses: actions/upload-artifact@v2
        with:
          name: firmware
          path: release/*
